### ISSUE TITLE
bump-my-version v0.28 is not packagesd

### ISSUE THREAD

**Issue by Zeitsperre** [conda-forge/bump-my-version-feedstock#43]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

It seems as though the dependencies weren't updated between v0.27 and v0.28 as the package failed to build here.

I believe that `conda-forge` asks that maintainers add the build backend to the `build` section now (errors on are showing that `hatchling` was not installed).

### Installed packages

N/A

### Environment info

N/A

**Comment by mfisher87** [comment]
Great catch, thank you! 👀 

I will likely not bother with 0.28.0 and roll forward fixing 0.28.1.
